import importlib.util
import contextlib
import io
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import types
import unittest
from unittest.mock import Mock, patch


def module(name, filename):
    spec = importlib.util.spec_from_file_location(name, Path(__file__).parents[1] / "scripts" / filename)
    result = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(result)
    return result


cleanup = module("small_cleanup", "clean_windows_small_artifacts.py")
guard = vars(module("small_guard", "clean_windows_generated_files.py"))


class SmallCleanupTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        subprocess.run(["git", "init", "-q", str(self.root)], check=True)

    def file(self, name, contents=b"keep"):
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(contents)
        return path

    def cache(self, directory="services", name="module", opt=""):
        source = self.file(f"{directory}/{name}.py", b"# local code\n")
        bytecode = self.file(f"{directory}/__pycache__/{name}.cpython-311{opt}.pyc", b"generated bytecode")
        return source, bytecode

    def clean(self, protected=()):
        records, directories, review, skipped = cleanup.make_plan(self.root, guard, protected)
        log = self.root / "deleted.jsonl"
        cleanup.clean(self.root, records, directories, guard, log)
        return records, review, skipped

    def test_source_and_untracked_modifications_are_preserved(self):
        source, bytecode = self.cache(opt=".opt-1")
        code = self.file("app/ui2/assets/windows_startup_local.js", b"local startup customization")
        self.clean()
        self.assertTrue(source.exists())
        self.assertEqual(code.read_bytes(), b"local startup customization")
        self.assertFalse(bytecode.exists())
        self.assertFalse(bytecode.parent.exists())

    def test_sourceless_bytecode_is_preserved_for_review(self):
        orphan = self.file("app/__pycache__/orphan.cpython-311.pyc")
        records, review, _ = self.clean()
        self.assertFalse(records)
        self.assertEqual(review[0]["reason"], "bytecode_sin_fuente_identificable")
        self.assertTrue(orphan.exists())

    def test_pytest_versioned_bytecode_is_removed_with_source_preserved(self):
        source = self.file("tests/test_case.py", b"# current test source")
        bytecode = self.file("tests/__pycache__/test_case.cpython-311-pytest-8.4.1.pyc")
        records, _, _ = self.clean()
        self.assertEqual(len(records), 1)
        self.assertTrue(source.exists())
        self.assertFalse(bytecode.exists())

    def test_obsolete_test_bytecode_removed_only_with_preserved_obsolete_source(self):
        source = self.file("tests/test_case.py.obsolete", b"# preserved obsolete test")
        bytecode = self.file("tests/__pycache__/test_case.cpython-311-pytest-8.4.1.pyc")
        regular = self.file("tests/__pycache__/test_case.cpython-311.pyc")
        records, _, _ = self.clean()
        self.assertEqual(len(records), 2)
        self.assertTrue(source.exists())
        self.assertFalse(bytecode.exists())
        self.assertFalse(regular.exists())

    def test_unrecognized_pytest_suffix_is_preserved(self):
        self.file("tests/test_case.py")
        bytecode = self.file("tests/__pycache__/test_case.cpython-311-pytest-custom.pyc")
        self.clean()
        self.assertTrue(bytecode.exists())

    def test_tracked_cache_is_preserved(self):
        _, bytecode = self.cache()
        subprocess.run(["git", "-C", str(self.root), "add", str(bytecode.relative_to(self.root))], check=True)
        self.clean()
        self.assertTrue(bytecode.exists())

    def test_runtime_library_venv_git_backup_installed_app_builds_are_not_traversed(self):
        protected_files = []
        for name in ("runtime", "data_test", ".venv", "backups", "knowledge", ".lexia_windows_app", ".build_lexia_windows", "unrecognized"):
            _, bytecode = self.cache(directory=name)
            protected_files.append(bytecode)
        self.file(".git/Thumbs.db", b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1")
        records, _, _ = self.clean()
        self.assertFalse(records)
        self.assertTrue(all(path.exists() for path in protected_files))
        self.assertTrue((self.root / ".git/Thumbs.db").exists())

    def test_configured_custom_library_inside_source_directory_is_preserved(self):
        _, bytecode = self.cache("app/custom_library")
        protected = [self.root / "app/custom_library"]
        self.clean(protected)
        self.assertTrue(bytecode.exists())

    def test_backup_folders_and_temp_files_preserved_for_review(self):
        _, backup_cache = self.cache("app/ui2/backup_20261001")
        copy = self.file("app/ui2/index.html.respaldo-busqueda-20260930")
        temporary = self.file("services/unfinished.tmp")
        installer = self.file("scripts/install_study_truncation_macos.py")
        _, review, skipped = self.clean()
        self.assertEqual({record["path"] for record in review},
                         {str(path.relative_to(self.root)) for path in (copy, temporary, installer)})
        self.assertTrue(all(path.exists() for path in (copy, temporary, installer, backup_cache)))
        self.assertTrue(any(item["path"] == "app/ui2/backup_20261001" for item in skipped))
        inventory = cleanup.backup_folder_inventory(self.root, skipped, guard)
        self.assertEqual(inventory[0]["files_total"], 2)
        self.assertEqual({item["path"] for item in inventory[0]["files"]},
                         {"app/ui2/backup_20261001/module.py", "app/ui2/backup_20261001/__pycache__/module.cpython-311.pyc"})

    def test_verified_os_caches_only(self):
        finder = self.file("app/.DS_Store", b"\x00\x00\x00\x01Bud1rest")
        thumbs = self.file("app/Thumbs.db", b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1rest")
        uncertain = self.file("services/Thumbs.db", b"not a cache")
        self.clean()
        self.assertFalse(finder.exists())
        self.assertFalse(thumbs.exists())
        self.assertTrue(uncertain.exists())

    def test_pytest_cache_unknown_file_is_preserved_and_known_files_removed(self):
        tag = self.file(".pytest_cache/CACHEDIR.TAG", cleanup.TEST_CACHE_TAG + b"\n# generated\n")
        nodes = self.file(".pytest_cache/v/cache/nodeids", b"[]")
        user = self.file(".pytest_cache/v/cache/custom_notes.txt", b"unique notes")
        self.clean()
        self.assertFalse(tag.exists())
        self.assertFalse(nodes.exists())
        self.assertTrue(user.exists())

    def test_cache_without_pytest_signature_is_preserved(self):
        nodes = self.file(".pytest_cache/v/cache/nodeids", b"[]")
        self.clean()
        self.assertTrue(nodes.exists())

    def test_changed_file_blocks_unlink(self):
        _, bytecode = self.cache()
        records, directories, _, _ = cleanup.make_plan(self.root, guard)
        bytecode.write_bytes(b"changed while planning")
        with self.assertRaisesRegex(ValueError, "cambio"):
            cleanup.clean(self.root, records, directories, guard, self.root / "deleted.jsonl")
        self.assertTrue(bytecode.exists())

    @unittest.skipIf(sys.platform == "win32", "Symlink creation needs Windows privilege")
    def test_links_and_directory_links_are_skipped(self):
        outside = self.root / "outside"
        outside.mkdir()
        external = outside / ".DS_Store"
        external.write_bytes(b"\x00\x00\x00\x01Bud1")
        (self.root / "app").mkdir()
        (self.root / "app/link").symlink_to(outside, target_is_directory=True)
        (self.root / "app/Thumbs.db").symlink_to(external)
        _, _, skipped = self.clean()
        self.assertTrue(external.exists())
        self.assertEqual(sum(item["reason"] == "enlace_conservado" for item in skipped), 2)

    def test_large_artifacts_are_not_removed(self):
        _, bytecode = self.cache()
        bytecode.write_bytes(b"x" * (cleanup.MAX_BYTES + 1))
        self.clean()
        self.assertTrue(bytecode.exists())

    def test_windows_main_saves_audit_deletion_log_and_completion(self):
        source, bytecode = self.cache()
        keep = self.file("services/local.py.bak")
        settings = types.SimpleNamespace(__dataclass_fields__={"library_path": None},
                                         library_path=self.root / "data_test")
        tested_guard = dict(guard, check_stopped=Mock())
        with patch.object(sys, "platform", "win32"), \
                patch.object(sys, "argv", ["cleaner.py", "--root", str(self.root), "--apply"]), \
                patch.object(sys, "path", sys.path[:]), \
                patch.object(cleanup, "load_guard", return_value=tested_guard), \
                patch.dict(sys.modules, {"config.settings": types.SimpleNamespace(SETTINGS=settings)}), \
                contextlib.redirect_stdout(io.StringIO()):
            cleanup.main()
        self.assertFalse(bytecode.exists())
        self.assertTrue(source.exists())
        self.assertTrue(keep.exists())
        tested_guard["check_stopped"].assert_called()
        self.assertEqual(tested_guard["check_stopped"].call_count, 2)
        report = json.loads(next((self.root / "logs").glob("*.json")).read_text())
        self.assertTrue(report["cleanup_completed"])
        self.assertEqual(report["files_removed"], 1)
        self.assertEqual(report["review_preserved"][0]["path"], "services/local.py.bak")
        self.assertEqual(len(list((self.root / "logs").glob("*.jsonl"))), 1)

    def test_report_does_not_hide_local_backups_behind_bytecode_list(self):
        for i in range(90):
            self.file(f"tests/__pycache__/test_orphan{i}.cpython-311.pyc")
        self.file("app/ui2/index.html.bak")
        tested_guard = dict(guard, check_stopped=Mock())
        settings = types.SimpleNamespace(__dataclass_fields__={})
        with patch.object(sys, "platform", "win32"), \
                patch.object(sys, "argv", ["cleaner.py", "--root", str(self.root)]), \
                patch.object(sys, "path", sys.path[:]), \
                patch.object(cleanup, "load_guard", return_value=tested_guard), \
                patch.dict(sys.modules, {"config.settings": types.SimpleNamespace(SETTINGS=settings)}), \
                contextlib.redirect_stdout(io.StringIO()) as output:
            cleanup.main()
        displayed = json.JSONDecoder().raw_decode(output.getvalue())[0]
        self.assertEqual(displayed["bytecode_preserved_total"], 90)
        self.assertEqual(len(displayed["bytecode_preserved_examples"]), 8)
        self.assertEqual(displayed["review_preserved"][0]["path"], "app/ui2/index.html.bak")


if __name__ == "__main__":
    unittest.main()
