import importlib.util
import contextlib
import io
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import types
import unittest
import zipfile
from unittest.mock import Mock, patch


def module(name, filename):
    spec = importlib.util.spec_from_file_location(name, Path(__file__).parents[1] / "scripts" / filename)
    result = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(result)
    return result


cleanup = module("small_cleanup", "clean_windows_small_artifacts.py")
guard = vars(module("small_guard", "clean_windows_generated_files.py"))


class SmallCleanupTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        subprocess.run(["git", "init", "-q", str(self.root)], check=True)

    def file(self, name, contents=b"keep"):
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(contents)
        return path

    def cache(self, directory="services", name="module", opt=""):
        source = self.file(f"{directory}/{name}.py", b"# local code\n")
        bytecode = self.file(f"{directory}/__pycache__/{name}.cpython-311{opt}.pyc", b"generated bytecode")
        return source, bytecode

    def clean(self, protected=()):
        records, directories, review, skipped = cleanup.make_plan(self.root, guard, protected)
        log = self.root / "deleted.jsonl"
        cleanup.clean(self.root, records, directories, guard, log)
        return records, review, skipped

    def test_source_and_untracked_modifications_are_preserved(self):
        source, bytecode = self.cache(opt=".opt-1")
        code = self.file("app/ui2/assets/windows_startup_local.js", b"local startup customization")
        self.clean()
        self.assertTrue(source.exists())
        self.assertEqual(code.read_bytes(), b"local startup customization")
        self.assertFalse(bytecode.exists())
        self.assertFalse(bytecode.parent.exists())

    def test_sourceless_bytecode_is_preserved_for_review(self):
        orphan = self.file("app/__pycache__/orphan.cpython-311.pyc")
        records, review, _ = self.clean()
        self.assertFalse(records)
        self.assertEqual(review[0]["reason"], "bytecode_sin_fuente_identificable")
        self.assertTrue(orphan.exists())

    def test_pytest_versioned_bytecode_is_removed_with_source_preserved(self):
        source = self.file("tests/test_case.py", b"# current test source")
        bytecode = self.file("tests/__pycache__/test_case.cpython-311-pytest-8.4.1.pyc")
        records, _, _ = self.clean()
        self.assertEqual(len(records), 1)
        self.assertTrue(source.exists())
        self.assertFalse(bytecode.exists())

    def test_obsolete_test_bytecode_removed_only_with_preserved_obsolete_source(self):
        source = self.file("tests/test_case.py.obsolete", b"# preserved obsolete test")
        bytecode = self.file("tests/__pycache__/test_case.cpython-311-pytest-8.4.1.pyc")
        regular = self.file("tests/__pycache__/test_case.cpython-311.pyc")
        records, _, _ = self.clean()
        self.assertEqual(len(records), 2)
        self.assertTrue(source.exists())
        self.assertFalse(bytecode.exists())
        self.assertFalse(regular.exists())

    def test_unrecognized_pytest_suffix_is_preserved(self):
        self.file("tests/test_case.py")
        bytecode = self.file("tests/__pycache__/test_case.cpython-311-pytest-custom.pyc")
        self.clean()
        self.assertTrue(bytecode.exists())

    def test_tracked_cache_is_preserved(self):
        _, bytecode = self.cache()
        subprocess.run(["git", "-C", str(self.root), "add", str(bytecode.relative_to(self.root))], check=True)
        self.clean()
        self.assertTrue(bytecode.exists())

    def test_runtime_library_venv_git_backup_installed_app_builds_are_not_traversed(self):
        protected_files = []
        for name in ("runtime", "data_test", ".venv", "backups", "knowledge", ".lexia_windows_app", ".build_lexia_windows", "unrecognized"):
            _, bytecode = self.cache(directory=name)
            protected_files.append(bytecode)
        self.file(".git/Thumbs.db", b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1")
        records, _, _ = self.clean()
        self.assertFalse(records)
        self.assertTrue(all(path.exists() for path in protected_files))
        self.assertTrue((self.root / ".git/Thumbs.db").exists())

    def test_configured_custom_library_inside_source_directory_is_preserved(self):
        _, bytecode = self.cache("app/custom_library")
        protected = [self.root / "app/custom_library"]
        self.clean(protected)
        self.assertTrue(bytecode.exists())

    def test_backup_folders_and_temp_files_preserved_for_review(self):
        _, backup_cache = self.cache("app/ui2/backup_20261001")
        copy = self.file("app/ui2/index.html.respaldo-busqueda-20260930")
        temporary = self.file("services/unfinished.tmp")
        installer = self.file("scripts/install_study_truncation_macos.py")
        _, review, skipped = self.clean()
        self.assertEqual({record["path"] for record in review},
                         {str(path.relative_to(self.root)) for path in (copy, temporary, installer)})
        self.assertTrue(all(path.exists() for path in (copy, temporary, installer, backup_cache)))
        self.assertTrue(any(item["path"] == "app/ui2/backup_20261001" for item in skipped))
        inventory = cleanup.backup_folder_inventory(self.root, skipped, guard)
        self.assertEqual(inventory[0]["files_total"], 2)
        self.assertEqual({item["path"] for item in inventory[0]["files"]},
                         {"app/ui2/backup_20261001/module.py", "app/ui2/backup_20261001/__pycache__/module.cpython-311.pyc"})

    def test_verified_os_caches_only(self):
        finder = self.file("app/.DS_Store", b"\x00\x00\x00\x01Bud1rest")
        thumbs = self.file("app/Thumbs.db", b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1rest")
        uncertain = self.file("services/Thumbs.db", b"not a cache")
        self.clean()
        self.assertFalse(finder.exists())
        self.assertFalse(thumbs.exists())
        self.assertTrue(uncertain.exists())

    def test_pytest_cache_unknown_file_is_preserved_and_known_files_removed(self):
        tag = self.file(".pytest_cache/CACHEDIR.TAG", cleanup.TEST_CACHE_TAG + b"\n# generated\n")
        nodes = self.file(".pytest_cache/v/cache/nodeids", b"[]")
        user = self.file(".pytest_cache/v/cache/custom_notes.txt", b"unique notes")
        self.clean()
        self.assertFalse(tag.exists())
        self.assertFalse(nodes.exists())
        self.assertTrue(user.exists())

    def test_cache_without_pytest_signature_is_preserved(self):
        nodes = self.file(".pytest_cache/v/cache/nodeids", b"[]")
        self.clean()
        self.assertTrue(nodes.exists())

    def test_changed_file_blocks_unlink(self):
        _, bytecode = self.cache()
        records, directories, _, _ = cleanup.make_plan(self.root, guard)
        bytecode.write_bytes(b"changed while planning")
        with self.assertRaisesRegex(ValueError, "cambio"):
            cleanup.clean(self.root, records, directories, guard, self.root / "deleted.jsonl")
        self.assertTrue(bytecode.exists())

    @unittest.skipIf(sys.platform == "win32", "Symlink creation needs Windows privilege")
    def test_links_and_directory_links_are_skipped(self):
        outside = self.root / "outside"
        outside.mkdir()
        external = outside / ".DS_Store"
        external.write_bytes(b"\x00\x00\x00\x01Bud1")
        (self.root / "app").mkdir()
        (self.root / "app/link").symlink_to(outside, target_is_directory=True)
        (self.root / "app/Thumbs.db").symlink_to(external)
        _, _, skipped = self.clean()
        self.assertTrue(external.exists())
        self.assertEqual(sum(item["reason"] == "enlace_conservado" for item in skipped), 2)

    def test_large_artifacts_are_not_removed(self):
        _, bytecode = self.cache()
        bytecode.write_bytes(b"x" * (cleanup.MAX_BYTES + 1))
        self.clean()
        self.assertTrue(bytecode.exists())

    def test_windows_main_saves_audit_deletion_log_and_completion(self):
        source, bytecode = self.cache()
        keep = self.file("services/local.py.bak")
        settings = types.SimpleNamespace(__dataclass_fields__={"library_path": None},
                                         library_path=self.root / "data_test")
        tested_guard = dict(guard, check_stopped=Mock())
        with patch.object(sys, "platform", "win32"), \
                patch.object(sys, "argv", ["cleaner.py", "--root", str(self.root), "--apply"]), \
                patch.object(sys, "path", sys.path[:]), \
                patch.object(cleanup, "load_guard", return_value=tested_guard), \
                patch.dict(sys.modules, {"config.settings": types.SimpleNamespace(SETTINGS=settings)}), \
                contextlib.redirect_stdout(io.StringIO()):
            cleanup.main()
        self.assertFalse(bytecode.exists())
        self.assertTrue(source.exists())
        self.assertTrue(keep.exists())
        tested_guard["check_stopped"].assert_called()
        self.assertEqual(tested_guard["check_stopped"].call_count, 2)
        report = json.loads(next((self.root / "logs").glob("*.json")).read_text())
        self.assertTrue(report["cleanup_completed"])
        self.assertEqual(report["files_removed"], 1)
        self.assertEqual(report["review_preserved"][0]["path"], "services/local.py.bak")
        self.assertEqual(len(list((self.root / "logs").glob("*.jsonl"))), 1)

    def test_report_does_not_hide_local_backups_behind_bytecode_list(self):
        for i in range(90):
            self.file(f"tests/__pycache__/test_orphan{i}.cpython-311.pyc")
        self.file("app/ui2/index.html.bak")
        tested_guard = dict(guard, check_stopped=Mock())
        settings = types.SimpleNamespace(__dataclass_fields__={})
        with patch.object(sys, "platform", "win32"), \
                patch.object(sys, "argv", ["cleaner.py", "--root", str(self.root)]), \
                patch.object(sys, "path", sys.path[:]), \
                patch.object(cleanup, "load_guard", return_value=tested_guard), \
                patch.dict(sys.modules, {"config.settings": types.SimpleNamespace(SETTINGS=settings)}), \
                contextlib.redirect_stdout(io.StringIO()) as output:
            cleanup.main()
        displayed = json.JSONDecoder().raw_decode(output.getvalue())[0]
        self.assertEqual(displayed["bytecode_preserved_total"], 90)
        self.assertEqual(len(displayed["bytecode_preserved_examples"]), 8)
        self.assertEqual(displayed["review_preserved"][0]["path"], "app/ui2/index.html.bak")

    def consolidate(self, protected=(), stamp="test"):
        _, review, skipped = self.clean_plan(protected)
        folders = cleanup.backup_folder_inventory(self.root, skipped, guard)
        (self.root / "logs").mkdir(exist_ok=True)
        return cleanup.consolidate_reviewed(self.root, review, folders, protected,
                                           dict(guard, check_stopped=Mock()), stamp)

    def clean_plan(self, protected=()):
        records, _, review, skipped = cleanup.make_plan(self.root, guard, protected)
        return records, review, skipped

    def test_consolidation_archives_reviewed_files_and_preserves_current_code(self):
        current = self.file("storage/catalog.py", b"current catalog code")
        backup = self.file("storage/catalog.py.bak_logfix_batch2", b"unique old code")
        installer = self.file("scripts/install_pr24_windows.py", b"old installer")
        orphan = self.file("storage/__pycache__/catalog.py.batch2.cpython-311.pyc", b"unique bytecode")
        ui = self.file("app/ui2/index.html", b"current customized UI")
        ui_backup = self.file("app/ui2/backup_ui2_331a_20260816_151234/index.html", b"old unique UI")
        untouched = self.file("services/unfinished.tmp", b"possible pending work")
        originals = {path.relative_to(self.root).as_posix(): path.read_bytes()
                     for path in (backup, installer, orphan, ui_backup)}
        result = self.consolidate()
        self.assertEqual(result["files_consolidated"], 4)
        with zipfile.ZipFile(result["archive"]) as package:
            for name, content in originals.items():
                self.assertEqual(package.read(name), content)
        self.assertTrue(all(not (self.root / name).exists() for name in originals))
        self.assertEqual(current.read_bytes(), b"current catalog code")
        self.assertEqual(ui.read_bytes(), b"current customized UI")
        self.assertTrue(untouched.exists())
        self.assertEqual(self.consolidate(stamp="retry")["files_consolidated"], 0)

    def test_referenced_artifact_is_not_archived_or_deleted(self):
        self.file("storage/catalog.py")
        backup = self.file("storage/catalog.py.bak_logfix_batch2")
        self.file("services/loader.py", b"source = 'catalog.py.bak_logfix_batch2'")
        result = self.consolidate()
        self.assertEqual(result["files_consolidated"], 0)
        self.assertEqual(result["preserved"][0]["reason"], "referencia_en_codigo_local")
        self.assertTrue(backup.exists())

    def test_archive_validation_failure_preserves_all_originals(self):
        self.file("storage/catalog.py")
        backup = self.file("storage/catalog.py.bak_logfix_batch2", b"unique old code")
        with patch.object(zipfile.ZipFile, "testzip", return_value="corrupt entry"):
            with self.assertRaisesRegex(ValueError, "CRC"):
                self.consolidate()
        self.assertEqual(backup.read_bytes(), b"unique old code")

    def test_source_change_after_archive_verification_blocks_removal(self):
        self.file("storage/catalog.py")
        backup = self.file("storage/catalog.py.bak_logfix_batch2", b"unique old code")
        original_digest = guard["digest"]
        calls = 0
        def changed_digest(path):
            nonlocal calls
            calls += 1
            if calls == 2:
                backup.write_bytes(b"new unique old code")
            return original_digest(path)
        with patch.dict(guard, {"digest": changed_digest}):
            with self.assertRaisesRegex(ValueError, "cambio"):
                self.consolidate()
        self.assertEqual(backup.read_bytes(), b"new unique old code")

    def test_tracked_backup_and_configured_artifact_are_preserved(self):
        self.file("storage/catalog.py")
        tracked = self.file("storage/catalog.py.bak_logfix_batch2")
        configured = self.file("scripts/install_pr24_windows.py")
        subprocess.run(["git", "-C", str(self.root), "add", str(tracked.relative_to(self.root))], check=True)
        result = self.consolidate(protected=[configured])
        self.assertEqual(result["files_consolidated"], 0)
        self.assertTrue(tracked.exists())
        self.assertTrue(configured.exists())

    def test_backup_with_additional_files_is_not_consolidated(self):
        self.file("app/ui2/index.html")
        old = self.file("app/ui2/backup_ui2_331a_20260816_151234/index.html")
        unique = self.file("app/ui2/backup_ui2_331a_20260816_151234/unique_notes.txt")
        self.assertEqual(self.consolidate()["files_consolidated"], 0)
        self.assertTrue(old.exists())
        self.assertTrue(unique.exists())

    def test_missing_current_source_keeps_historical_copy(self):
        backup = self.file("storage/catalog.py.bak_logfix_batch2")
        result = self.consolidate()
        self.assertEqual(result["files_consolidated"], 0)
        self.assertEqual(result["preserved"][0]["reason"], "falta_el_archivo_operativo_actual")
        self.assertTrue(backup.exists())


if __name__ == "__main__":
    unittest.main()
